import './globals.css';
import Header from '../../ui/header/Header';

export const metadata = {
  title: 'dongbin',
  description: 'Generated by dongbin yoo',
};

export default function RootLayout({
  children, // will be a page or nexted layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
