import './globals.css';

export const metadata = {
  title: 'yoo.com',
  description: 'Generated by dongbin yoo',
};

export default function RootLayout({
  children, // will be a page or nexted layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
