import './globals.css';
// import LayoutProvider from './LayoutProvider';
import Header from '@/ui/Header/Header';
import Footer from '@/ui/Footer/Footer';

export const metadata = {
  title: 'dongbin',
  description: 'Generated by dongbin yoo',
};

export default function RootLayout({
  children, // will be a page or nexted layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
